### ISSUE TITLE
共享几个在我onenote里的想法，加油

### ISSUE THREAD

**Issue by a1exwang** [little-game-and-simple-software/idea-show2#3]
- 做一个30min长的音乐，并且不完全重复，不奇怪
- 在 soundbetter.com 或者www.airgigs.com这类租赁网站上，租一个歌手录 kawaii bass 采样音效
- 用三个和弦，但允许和弦类型的变化，做一首音乐，并且不显得单调。比如只用 C，F，G 三个和弦，但可以用C7sus Fmaj7 G9sus/C 这些，但不能用Am，Em
- 用 vocal chop + harmor  resynthesis 做 lead
- 一条旋律线上相邻的音符交替使用不同的lead演奏（比如square，super saw，sine，pluck）。例如 HoneyComeBear - Natsuzora(ナツゾラ)(20XX Remix)
- 用 vocal chop 去 sidechain 压缩其他音色，或者甚至把 vocal chop 当打击乐器用

**Comment by 2439905184** [comment]
好

**Comment by 2439905184** [comment]
已添加

**Comment by 2439905184** [comment]
我做的 新的东西 来看看吗
全站游戏搜索工具 目前没有完善
有taptap的搜索功能
核心原理是html表单提交 
这是我自己的需求 
也可能是一些玩家的需求
后期会添加筛选功能
直达式站内搜索 不像百度 有广告 或者搜到别的东西 

https://github.com/2439905184/you_search/tree/gh-pages

**Comment by 2439905184** [comment]
和网址导航很类似的 但是这种是直达式搜索
属于精准搜索的那种类型
我就是想要快速的搜到我要找的东西
一个一个网站去用他们的站内搜索
太慢了
直接一键式多个网站直达搜索多爽
如果要搜别的东西 想要得到五花八门的结果
这个是不适合的 那种需求用百度就行
我这个是精确搜索 目标明确
